# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 20:48
from __future__ import unicode_literals

import Airline.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNo', models.CharField(blank=True, default='Airbus A320', max_length=15)),
                ('capacity', models.IntegerField(blank=True, default=180)),
                ('registrationNumber', models.CharField(blank=True, default=807131, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNR', models.CharField(default=401407, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Date')),
                ('flightNum', models.CharField(max_length=50, unique=True)),
                ('price', models.CharField(max_length=10)),
                ('arrivalTime', models.CharField(max_length=10)),
                ('departureTime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OperatedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Flights')),
                ('registrationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30, validators=[Airline.models.verify_email])),
                ('PhoneNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('FirstName', models.CharField(max_length=30, validators=[Airline.models.validateName])),
                ('LastName', models.CharField(blank=True, max_length=30, validators=[Airline.models.validateName])),
                ('Sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Age', models.IntegerField(validators=[Airline.models.validate_age])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNR', models.CharField(blank=True, default='RRgP5q', max_length=6)),
                ('price', models.CharField(default=186, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='PNR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Ticket'),
        ),
        migrations.AddField(
            model_name='issuedfor',
            name='PNR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Ticket', unique=True),
        ),
        migrations.AddField(
            model_name='issuedfor',
            name='flightNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Flights'),
        ),
        migrations.AlterUniqueTogether(
            name='operatedby',
            unique_together=set([('flightNum', 'registrationNumber')]),
        ),
    ]
