# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='phone_number',
            new_name='PhoneNumber',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='sex',
            new_name='Sex',
        ),
    ]
