# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0002_auto_20170407_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatedby',
            old_name='date',
            new_name='dt',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='registrationNumber',
            field=models.CharField(blank=True, default=147200, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PNR',
            field=models.CharField(blank=True, default='BcAZxe', max_length=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(default=184, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='operatedby',
            unique_together=set([('flightNum', 'dt')]),
        ),
    ]
