# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 18:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0002_auto_20170329_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNR', models.CharField(default=617512, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Date')),
                ('flightNum', models.CharField(max_length=50, unique=True)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=116)),
                ('PNR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Booking')),
            ],
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='PhoneNumber',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='booking',
            name='PhoneNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Passenger'),
        ),
    ]
