# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0003_auto_20170330_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='arrivalTime',
            field=models.CharField(default=datetime.datetime(2017, 3, 30, 19, 57, 10, 683120, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flights',
            name='departureTime',
            field=models.CharField(default=datetime.datetime(2017, 3, 30, 19, 57, 23, 656740, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='PNR',
            field=models.CharField(default=237399, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=632),
        ),
    ]
