# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0004_auto_20170330_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNo', models.CharField(blank=True, default='Airbus A320', max_length=15)),
                ('capacity', models.IntegerField(blank=True, default=180)),
                ('registrationNumber', models.CharField(blank=True, default=665610, max_length=6, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='PNR',
            field=models.CharField(default=194787, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=839),
        ),
    ]
