# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0005_auto_20170331_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Flights')),
            ],
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='registrationNumber',
            field=models.CharField(blank=True, default=495154, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='PNR',
            field=models.CharField(default=448632, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=352),
        ),
        migrations.AddField(
            model_name='operatedby',
            name='registrationNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Aircraft'),
        ),
        migrations.AlterUniqueTogether(
            name='operatedby',
            unique_together=set([('flightNum', 'registrationNumber')]),
        ),
    ]
