# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0006_auto_20170407_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='registrationNumber',
            field=models.CharField(blank=True, default=290283, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='seatsAvailable',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PNR',
            field=models.CharField(blank=True, default='7biJFT', max_length=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(default=571, max_length=10),
        ),
    ]
