# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0007_auto_20170407_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='capacity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='registrationNumber',
            field=models.CharField(blank=True, default=266282, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PNR',
            field=models.CharField(blank=True, default='0oUk6I', max_length=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(default=416, max_length=10),
        ),
    ]
