# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0011_auto_20170331_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='registrationNumber',
            field=models.CharField(blank=True, default=801389, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='PNR',
            field=models.CharField(default=493637, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PNR',
            field=models.CharField(blank=True, default='Xg5OYi', max_length=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='issuedfor',
            name='PNR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Ticket'),
        ),
        migrations.AddField(
            model_name='issuedfor',
            name='flightNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.Flights'),
        ),
    ]
