# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-02 12:21
from __future__ import unicode_literals

import Airline.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0017_auto_20170402_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='registrationNumber',
            field=models.CharField(blank=True, default=642655, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='PNR',
            field=models.CharField(default=341461, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Email',
            field=models.CharField(max_length=30, validators=[Airline.models.verify_email]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='PhoneNumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PNR',
            field=models.CharField(blank=True, default='T6iZoR', max_length=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(default=637, max_length=10),
        ),
    ]
