# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-02 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0018_auto_20170402_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='registrationNumber',
            field=models.CharField(blank=True, default=742838, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='PNR',
            field=models.CharField(default=430761, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PNR',
            field=models.CharField(blank=True, default='Y5LIac', max_length=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(default=384, max_length=10),
        ),
    ]
